# Generated by scripts/gen_homebrew_formula.py — do not edit by hand.
#
# A mirror of the PyPI sdist: url/sha256 name the artifact release.yml published,
# and every dependency comes from the hash-pinned lock that ships inside that
# sdist. Homebrew would otherwise install from source (`--no-binary=:all:`),
# which for this dependency set means compiling MuPDF plus three Rust
# extensions: 20+ minutes per user, per release.
class ZoteroAgent < Formula
  include Language::Python::Virtualenv

  desc "Local read-write control of a Zotero library, from your terminal or AI agent"
  homepage "https://github.com/alex-roc/zotero-agent"
  url "https://files.pythonhosted.org/packages/source/z/zotero-agent/zotero_agent-0.4.0.tar.gz"
  sha256 "55f5e86e6177a0beecd7e05786115199a8b1ce967917c063bff51ae9be663a95"
  license "AGPL-3.0-or-later"

  depends_on "python@3.14"

  def install
    venv = virtualenv_create(libexec, "python3.14")

    # The extras, as wheels, from the lock that shipped with this sdist. `zot mcp`
    # and `zot toc` have to work on a plain `brew install`: a keg cannot gain them
    # later, since every upgrade replaces it.
    system Formula["python@3.14"].opt_libexec/"bin/python", "-m", "pip",
           "--python=#{libexec}/bin/python", "install", "--require-hashes",
           "--only-binary=:all:", "--no-deps", "--no-compile",
           "-r", buildpath/"packaging/homebrew/requirements.txt"

    # The package itself, which is pure Python and stdlib-only.
    venv.pip_install_and_link buildpath
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zot --version")

    # The reason this formula exists in this shape: the extras must be there.
    system libexec/"bin/python", "-c", "import mcp.server.fastmcp, pymupdf"

    # The agent surfaces ride inside the wheel; this fails if the sdist ever
    # stops carrying them.
    assert_predicate Pathname.new(shell_output("#{bin}/zot skill path").strip)/"SKILL.md", :exist?
  end
end
